### PR TITLE
add support for both light and dark appearances

### PR DESCRIPTION
**Pull request by samuelwford**
I know you may not be enthusiastic about it, but I really prefer to use the light appearance most of the time (my Mac is set to Auto for appearance and Dynamic for desktop).

The only colors I changed were to use system semantic colors & added alternate appearances for the theme colors. I also tweaked the status view to be a little more standard.

I understand if the changes aren't something you'd be willing to accept.

Nice work, otherwise!

### CODE REVIEW

**Comment by IvanMathy** [comment]
Hey there! Thanks for the PR, I'll review soon. I'm totally open to adding light mode, I might just implement it in a different way than you did for future compatibility with other features I have in mind.

Either way, light mode will make it into the next release.

**Comment by IvanMathy** [comment]
Hey! I ended up implementing a more dynamic version of your PR, that way we can swap it out later to have custom themes. Closing this one in favor of #61 

Thanks for the help!

**Comment by samuelwford** [comment]
No worries; thanks for considering it.

I will definitely checkout the other PR. Looking forward to the update.

**Comment by samuelwford** [comment]
The version is looking pretty good; it’s definitely an improvement over my changes.

Three minor nitpicks:

1. To my eye, the StatusView might look a little more “native” (?) with a border. In the awakeFromNib call:

        self.layer?.borderColor = NSColor.controlShadowColor.cgColor
        self.layer?.borderWidth = 1

2. The contrast between the text & the red background in the status view in light appearance is a little low.
3. I would be cool if the editor supported font size changes, like with cmd-plus & cmd-minus.

These really are just nitpicks, though.

**Pull request closed without merging**
