### PR TITLE
Add ShuffleLines and ShuffleCharacters scripts

### PR DESCRIPTION
**Pull request by fnky**
Add scripts for randomly shuffling lines and characters.

Shuffling in Boop

### CODE REVIEW

**Comment by fnky** [comment]
Seems like checks are failing due to duplication, which is unavoidable. Perhaps this could be relaxed a bit?

**Comment by IvanMathy** [comment]
Yeah the duplication filter is definitely a bit overzealous... I'm planning to add dependencies very soon so this will fix it, and I'll relax the rule a bit.

Is Shuffle Characters useful though? I can't really think of a use case that justifies putting it in the build in library...

**Comment by fnky** [comment]
I put it in as a convenience. I think having both the ability to work with lines as well as individual characters gives the user some choices. But if you don't think it'll add much value to Boop, then we can just get rid of it.

**Comment by IvanMathy** [comment]
Okay, so I went ahead and merged this into my content branch and moved the script. I'm closing this PR since I'll open a new one to merge back to main. That way the conflict is fixed, sonar won't complain and you get listed as a contributor. Thanks for the help!

**Pull request closed without merging**
