### PR TITLE
Add word counter script

### PR DESCRIPTION
**Pull request by daniel-stoneuk**
Addresses #97 

I didn't realise that writing a word counter script would be so difficult, but many word counters online count differently! For example, some don't count dashes as a word. For this script, to keep it simple, I've counted words as anything with a space around it and starts with a letter, number or ampersand symbol. (similar to https://wordcounter.net/)

The regex can be changed if you think of any better way to count words :)

### CODE REVIEW

**Comment by IvanMathy** [comment]
Hey there! Thanks for the contribution! 

It looks like there are two issues:

- An empty editor (or with only an emoji) causes an error
- Words with special characters (like à) work strangely, and words with only special chars don't get counted...

**Comment by daniel-stoneuk** [comment]
Hi @IvanMathy thanks so much for picking up on these. I knew I'd missed something and completely forgot about special characters whoops.

I'll fix these issues.

**Comment by daniel-stoneuk** [comment]
Really sorry about that! Reverted back to including dashes and other characters as words as well. Thanks

**Comment by IvanMathy** [comment]
Looks good, thank you!

**Pull request merged**
