### PR TITLE
Updated Icon for Big Sur

### PR DESCRIPTION
**Pull request by mmshivesh**
Hey, so I took a shot at updating the icon for Big Sur, I'd love to get your feedback on this icon.

icon_512x512@2x

Some thoughts about this icon:

1. Took design cues from Big Sur icons with depth and a smoother curve radius
2. Cleaned up gradient borders around the icon:

image

3. Uses the command icon from SF Symbols, leading to greater consistency with macOS Big Sur and beyond.

4. Due to smaller sizes expected by Big Sur icons (824x824 vs 1024x1024), the black padding around has been reduced while keeping the *character* of the icon intact.

5. Cleaner shadows around the command icon:

image

### CODE REVIEW

**Comment by mmshivesh** [comment]
This should also close #151.

**Comment by IvanMathy** [comment]
Hey there!

Thank you so much for the contribution! I think it looks great, my only concern is the very small icons being a bit blurry... I might redraw them on a smaller grid like the current one.

Would you mind sending me the working file?

Thanks!

**Comment by mmshivesh** [comment]
Thanks :)

[Here's](https://github.com/IvanMathy/Boop/files/5240864/Boop_Sketch.zip) the Sketch file I'm working on. This uses the Apple Design Resources icon template for macOS 11 Big Sur.

> my only concern is the very small icons being a bit blurry

Yes, this is 100% an issue where the command icon becomes a incomprehensible white blob at very small sizes, especially with:

1. 16px × 16px (@1x)
2. 16px × 16px (@2x) and 32px × 32px (@1x)
3. 32px × 32px (@2x)

This is something that I accidentally overlooked :/

**Comment by IvanMathy** [comment]
Awesome thanks! 

I created a version of Boop that should change the icon based on which version of the OS you have, could you confirm that it works? It's attached to this comment: [Boop-icon-test.zip](https://github.com/IvanMathy/Boop/files/5252072/Boop-icon-test.zip)


I'm planning to make the switch once macOS 11 is release publicly, but if we can have your icon in the next update for Big Sur that would be awesome.


Thanks!

**Comment by oliveratgithub** [comment]
@IvanMathy just tested it on macOS Big Sur 11.0 Beta (20A5364e) – it's still larger than even e.g. the Finder icon:

boop-icon-test app switcher big sur

boop-icon-test dock big sur

What do you think?

**Comment by IvanMathy** [comment]
Hmm.. That's unfortunate. Would you mind trying this build? If that doesn't work, we'll have to wait until Big Sur comes out.

[Boop-icon-test2.zip](https://github.com/IvanMathy/Boop/files/5252658/Boop-icon-test2.zip)

**Comment by oliveratgithub** [comment]
> Hmm.. That's unfortunate. Would you mind trying this build? If that doesn't work, we'll have to wait until Big Sur comes out.

@IvanMathy No changes visible as far as I can tell - still slightly too big…

Boop-icon-test2 Big Sur - App switcher
Boop-icon-test2 Big Sur - Dock

**Comment by mmshivesh** [comment]
@IvanMathy With the public release of Big Sur, I suggest we revisit this PR. I took another look at this icon and have implemented the suggested changes:

1. The biggest problem with visibility is because Apple uses a much larger padding size that shrinks the glyph down to 824x824 from 1024x1024. I redid the low resolution 16x16 images pixel-wise for high visibility:

icon_16x16


2. With many applications adopting the Big Sur icon style even in versions prior 11.0, I suggest we adopt the Big Sur icon style  even in prior versions

**Comment by IvanMathy** [comment]
Hey there, sorry for the huge delay in getting this merged... Thanks for all the help!

**Comment by narcistesa** [comment]
@IvanMathy will there be a new release with the updated icon? Thanks.

**Comment by mmshivesh** [comment]
@IvanMathy Thank you so much for the shoutout! Love your take on the icon. :)

**Pull request merged**
