### PR TITLE
Feat/light mode

### LINKED ISSUE #16: Light mode
The app doesn't look good in light mode. The UI is somewhat brown (I assume it mixes the color with my wallpaper), the content of the text field, is hardly readable.

image

### PR DESCRIPTION
**Pull request by IvanMathy**
Adding light mode, with preferences  Fixes #16 

Screen Shot 2020-06-18 at 18 58 52
Screen Shot 2020-06-18 at 18 58 27
Screen Shot 2020-06-18 at 18 58 19

### CODE REVIEW

**Comment by pcr910303** [comment]
@IvanMathy May I ask why the top bar is blue? Maybe it's just me, but I feel it a bit alien to the macOS theme.
I think the previous version was fine in dark mode, the native colors will look much better.

**Comment by IvanMathy** [comment]
@pcr910303 That's because I just ran a script that has an `info` call. It is white under normal conditions in light mode 👍

**Comment by pcr910303** [comment]
Oh, thanks for clarifying. Sorry for not testing and checking out myself :-(

**Comment by IvanMathy** [comment]
No worries at all, I'm happy you cared enough to raise the issue!

**Pull request merged**
