### PR TITLE
Added SHA1, SHA256, and SHA512 algorithms like done for MD5

### PR DESCRIPTION
**Pull request by dennis-menge**

### CODE REVIEW

**Comment by IvanMathy** [comment]
Hey there! First of all, let me apologize for the very late answer, I really thought I responded to this PR...

The reason the build is failing is because of code duplication. I'm about to merge a new PR (#104) which adds module support and would solve the issue. 

I can make my own version of your PR and consolidate the multiple scripts into a module, or you can push more commits to your branch so that you can get credit. I think this is a feature I'd love to have so I'd be happy to help out.

Thank you so much for the contribution, and once again sorry for not replying sooner...

**Comment by dennis-menge** [comment]
Hi, thank you for your answer. I did not take care about the duplication issue as I wanted to wait for your opinion first. I really like the module approach and would try to work on it.

**Comment by IvanMathy** [comment]
Sounds good! Here are some potential options:

- https://github.com/brix/crypto-js <-- This would need to be consolidated to work I believe
- https://github.com/h2non/jshashes#readme <-- This would probably work out of the box


Good luck!

**Comment by dennis-menge** [comment]
Hi @IvanMathy,
thank you so much for those references, I have added jshashes and adapted all related scripts.

**Comment by IvanMathy** [comment]
Perfect, thank you so much for the contribution!!

**Pull request merged**
