### PR TITLE
Add Support for Spongebob Sarcasm Text Script

### PR DESCRIPTION
**Pull request by psseelman**
This script randomly capitalizes letters to maKE yoUr TExt SaRCAstIC 

SpongeBoop

### CODE REVIEW

**Comment by IvanMathy** [comment]
OMG THIS IS GREAT

You need to understand how much this means to me... I used to work with @jayqi, author of https://github.comjayqi/spongebob

This was something that was used _a lot_. To the point that this was my goodbye message for him:

Screenshot of spongebobcase

I've been trying to get Jay to make a version of it for Boop for a very, very long time, including as recently as last week:

Screen Shot 2020-07-21 at 17 16 34

And, I mean, I strongly respect the effort you put to make this PR. This is masterful levels of shitposting and I love everything about it. I'm leaving the PR open for a couple days because more people need to see it. Thank you, really.

**Comment by psseelman** [comment]
Glad I could help!! Reading through the twitter conversation that started @jayqi version of it makes me laugh so hard. Love the app, keep up the good work my friend

**Comment by JacobSyndeo** [comment]
> AdD SuppOrt fOR sPoNGeBOb SaRCaSM texT ScriPt

(Good PR!)

**Comment by DonyThePony** [comment]
Amazing, I just had the exact same idea!
```
function main(input) {
    input.text = toSpongeCase(input.text);
}

function toSpongeCase(text) {
    var localText = text;
    var sponge = "";

    for (var i = 0; i < localText.length; i++) {
        if (localText.charAt(i).match(/[a-zA-Z]/)) {
            if (i % 2 == 0) {
                sponge = sponge + localText.charAt(i).toUpperCase();
            } else {
                sponge = sponge + localText.charAt(i).toLowerCase();
            }
        } else {
            sponge = sponge + localText.charAt(i)
        }
    }
    return sponge;
}
```

**Comment by IvanMathy** [comment]
It wOrKs GREat, THAnKS onCe aGAIN for THe cONtrIbUTIon!

**Pull request merged**
